// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByC1W8plcuf2FfqbuLud9sZ3-YHL3G2RI',
    appId: '1:837953915617:web:d8084329b258b7119f45a0',
    messagingSenderId: '837953915617',
    projectId: 'reviewmakanan-pabii',
    authDomain: 'reviewmakanan-pabii.firebaseapp.com',
    storageBucket: 'reviewmakanan-pabii.appspot.com',
    measurementId: 'G-9QJJTE1F39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDhIFdmL0LNNlaSq9C5xtLksj0ba77b6Q',
    appId: '1:837953915617:android:ac1ba3ac83423aa49f45a0',
    messagingSenderId: '837953915617',
    projectId: 'reviewmakanan-pabii',
    storageBucket: 'reviewmakanan-pabii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2tvz2lbqeABKWph7oVEwEKLIjTxvuHkM',
    appId: '1:837953915617:ios:86fd40f42b70c25b9f45a0',
    messagingSenderId: '837953915617',
    projectId: 'reviewmakanan-pabii',
    storageBucket: 'reviewmakanan-pabii.appspot.com',
    iosBundleId: 'com.example.reviewMakanan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2tvz2lbqeABKWph7oVEwEKLIjTxvuHkM',
    appId: '1:837953915617:ios:cb3db4a01e4fafcd9f45a0',
    messagingSenderId: '837953915617',
    projectId: 'reviewmakanan-pabii',
    storageBucket: 'reviewmakanan-pabii.appspot.com',
    iosBundleId: 'com.example.reviewMakanan.RunnerTests',
  );
}
