name: review_makanan
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.9
  flutter:
    sdk: flutter
  firebase_storage: ^11.7.6
  cloud_firestore: ^4.17.4
  path: ^1.9.0
  image_picker: ^1.1.1
  image_picker_web: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
